br:
  com:
    tasknote:
      server:
        jwt-secret: ${SECURITY_KEY:empty}
        target-env: ${TARGET_ENV:development}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost}
logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    br.com.tasknoteapp: TRACE

mailgun:
  api-key: ${MAILGUN_APIKEY:abc123456}
  domain: tasknoteapp.dev.br
  sender-email: no-reply@tasknoteapp.dev.br

server:
  port: 8585
  error:
    include-message: always
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/server}
spring:
  application:
    name: tasknote-api
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:default}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5435}/${POSTGRES_DB:tasknote}
    username: ${POSTGRES_USER:tasknoteuser}
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: tasknote
    show-sql: true
